---
Description: Cloudfront Distribution for Commonwealth Games
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CloudfrontLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  CloudfrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - bikeshop.brownie.com.au
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "POST"
            - "PUT"
            - "PATCH"
            - "OPTIONS"
            - "DELETE"
          Compress: True
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            Headers:
              - "*"
            QueryString: True
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: apigw-web
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: True
        HttpVersion: http2
        Origins:
          -
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - "TLSv1"
                - "TLSv1.1"
                - "TLSv1.2"
            DomainName: 1kmqbg6nn9.execute-api.ap-southeast-2.amazonaws.com
            Id: apigw-web
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:662430452979:certificate/80f287f8-4e33-4341-ada9-a6d2bf5bbe83"
          MinimumProtocolVersion: "TLSv1"
          SslSupportMethod: "sni-only"
